In [53]:
import pandas as pd

In [54]:
##A DataFrame is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, categorical data and more) in columns. 
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)
df
##Each column in a DataFrame is a Series

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

In [55]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

## Series

In [56]:
##creating series
series = pd.Series([100,102,104], name="Apartmentes", index=["apartment #1","apartment #2", "apartment #3"])
series

apartment #1    100
apartment #2    102
apartment #3    104
Name: Apartmentes, dtype: int64

In [57]:
print(series.loc)
print(series.loc["apartment #2"])    ##location by label
series.loc["apartment #2"] = 200
print(series.loc["apartment #2"])

<pandas.core.indexing._LocIndexer object at 0x000001FB14802250>
102
200

In [58]:
print(series.iloc[0])    ##integer location

100

In [59]:
##filter
print(series[series >= 103])

apartment #2    200
apartment #3    104
Name: Apartmentes, dtype: int64

In [60]:
calories = {"Day 1": 1750, "Day 2":2100, "Day 3":1750}
series2 = pd.Series(calories)
series2

Day 1    1750
Day 2    2100
Day 3    1750
dtype: int64

In [61]:
series2.loc["Day 3"] += 500
series2

Day 1    1750
Day 2    2100
Day 3    2250
dtype: int64

## DataFrame

In [62]:
data = {"Name": ["Spongebob","Patrick","Squidward"],
        "Age": [30,35,50]}
df = pd.DataFrame(data, index = ["Employee1","Employee2","Employee3"])      ##index is optional
df

                Name  Age
Employee1  Spongebob   30
Employee2    Patrick   35
Employee3  Squidward   50

In [63]:
print(type(df.loc["Employee2"]))
df.loc["Employee2"]

<class 'pandas.Series'>

Name    Patrick
Age          35
Name: Employee2, dtype: object

In [64]:
df.iloc[0]

Name    Spongebob
Age            30
Name: Employee1, dtype: object

In [65]:
## add a new column
df["Job"]= ["Cook","N/A","Cashier"]
df

                Name  Age      Job
Employee1  Spongebob   30     Cook
Employee2    Patrick   35      N/A
Employee3  Squidward   50  Cashier

In [66]:
## add a new row
new_rows = pd.DataFrame([{"Name":"Sandy", "Age":29 , "Job":"Doctor"}, {"Name":"Özge", "Age":28 , "Job":"Engineer"}],
                       index = ["Employee4","Employee5"])
df = pd.concat([df, new_rows])
df

                Name  Age       Job
Employee1  Spongebob   30      Cook
Employee2    Patrick   35       N/A
Employee3  Squidward   50   Cashier
Employee4      Sandy   29    Doctor
Employee5       Özge   28  Engineer

In [67]:
df["Age"].max()

np.int64(50)

In [68]:
df.describe()     ## describe() method provides a quick overview of the numerical data in a DataFrame

             Age
count   5.000000
mean   34.400000
std     9.126883
min    28.000000
25%    29.000000
50%    30.000000
75%    35.000000
max    50.000000

## Import CSV and JSON files

In [69]:
titanic = pd.read_csv("data/data.csv")  ## we can set "name" column as index by using index_col="Name"
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [70]:
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [71]:
titanic.tail(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

In [72]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [73]:
titanic.info()     ##a technical summary of a DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [74]:
## read_json and read_excel

## Select a subset

In [75]:
## selecting by column
survived = titanic["Survived"]
survived.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [76]:
titanic["Ticket"].shape

(891,)

In [77]:
age_sex = titanic[["Age", "Sex"]]
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [78]:
## filter
above_35 = titanic[titanic["Age"] > 35]
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [79]:
titanic["Survived"] == 1

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Survived, Length: 891, dtype: bool

In [80]:
class_2_and_3 = titanic[titanic["Pclass"].isin([2, 3])]    ## isin() conditional function returns a True for each row the values are in the provided list. 
class_2_and_3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [81]:
age_no_na = titanic[titanic["Age"].notna()]    ## The notna() conditional function returns a True for each row the values are not a Null value.
age_no_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [82]:
adult_names = titanic.loc[titanic["Age"] >= 18, "Name"]
adult_names.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [83]:
titanic.iloc[9:25, 2:5]   ## rows 9 till 25 and columns 3 to 5.

    Pclass                                               Name     Sex
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female
10       3                     Sandstrom, Miss Marguerite Rut  female
11       1                            Bonnell, Miss Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3                Vestrom, Miss Hulda Amanda Adolfina  female
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female
16       3                                Rice, Master Eugene    male
17       2                       Williams, Mr. Charles Eugene    male
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19       3                            Masselmani, Mrs. Fatima  female
20       2                               Fynney, Mr. Joseph J    male
21       2                              Beesley, Mr. Lawrence    male
22       3                         McGowan, Miss Anna "Annie"  female
23       1                       Sloper, Mr. William Thompson    male
24       3                       Palsson, Miss Torborg Danira  female

## Creating new columns derived from existing columns

In [84]:
air_quality = pd.read_csv("data/air_quality_no2.csv",index_col=0, parse_dates=True)
air_quality.head()

                     station_antwerp  station_paris  station_london
datetime
2019-05-07 02:00:00              NaN            NaN            23.0
2019-05-07 03:00:00             50.5           25.0            19.0
2019-05-07 04:00:00             45.0           27.7            19.0
2019-05-07 05:00:00              NaN           50.4            16.0
2019-05-07 06:00:00              NaN           61.9             NaN

In [85]:
air_quality["london_mg_per_cubic"] = air_quality["station_london"] * 1.882
air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic
datetime,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN

In [86]:
air_quality["ratio_paris_antwerp"] = (
    air_quality["station_paris"] / air_quality["station_antwerp"]
)
air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [87]:
## renaming the columns
air_quality_renamed = air_quality.rename(
    columns={
        "station_antwerp": "BETR801",
        "station_paris": "FR04014",
        "station_london": "London Westminster",
    }
)
air_quality_renamed.head()

,BETR801,FR04014,London Westminster,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [88]:
air_quality_renamed = air_quality_renamed.rename(columns=str.lower)

air_quality_renamed.head()

,betr801,fr04014,london westminster,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,35.758,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,35.758,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,30.112,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

## Calculate summary statistics

In [89]:
titanic["Age"].mean()

np.float64(29.69911764705882)

In [90]:
titanic[["Age", "Fare"]].median()

Age     28.0000
Fare    14.4542
dtype: float64

In [91]:
titanic[["Age", "Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [92]:
##nstead of the predefined statistics, specific combinations of aggregating statistics for given columns can be defined using the DataFrame.agg() method:
titanic.agg(
    {
        "Age": ["min", "max", "median", "skew"],
        "Fare": ["min", "max", "median", "mean"],
    }
)

              Age        Fare
min      0.420000    0.000000
max     80.000000  512.329200
median  28.000000   14.454200
skew     0.389108         NaN
mean          NaN   32.204208

### Aggregating statistics grouped by category

In [93]:
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [94]:
titanic.groupby("Sex").mean(numeric_only=True)    ## mean, sum, min ,max

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

In [95]:
titanic.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

### Count number of records by category

In [96]:
titanic["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## Reshape the layout

In [97]:
##sort
titanic.sort_values(by="Age", ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

### Long to wide table format

In [98]:
air_quality2 = pd.read_csv(
    "data/air_quality_long.csv", index_col="date.utc", parse_dates=True
)

# filter for no2 data only
no2 = air_quality2[air_quality2["parameter"] == "no2"]
# use 2 measurements (head) for each location (groupby)
no2_subset = no2.sort_index().groupby(["location"]).head(2)
no2_subset

,city,country,location,parameter,value,unit
date.utc,,,,,,
2019-04-09 01:00:00+00:00,Antwerpen,BE,BETR801,no2,22.5,µg/m³
2019-04-09 01:00:00+00:00,Paris,FR,FR04014,no2,24.4,µg/m³
2019-04-09 02:00:00+00:00,London,GB,London Westminster,no2,67.0,µg/m³
2019-04-09 02:00:00+00:00,Antwerpen,BE,BETR801,no2,53.5,µg/m³
2019-04-09 02:00:00+00:00,Paris,FR,FR04014,no2,27.4,µg/m³
2019-04-09 03:00:00+00:00,London,GB,London Westminster,no2,67.0,µg/m³

In [99]:
no2_subset.pivot(columns="location", values="value")   ##The pivot() function is purely reshaping of the data: a single value for each index/column combination is required.

location                   BETR801  FR04014  London Westminster
date.utc
2019-04-09 01:00:00+00:00     22.5     24.4                 NaN
2019-04-09 02:00:00+00:00     53.5     27.4                67.0
2019-04-09 03:00:00+00:00      NaN      NaN                67.0

In [100]:
##In the case of pivot(), the data is only rearranged. When multiple values need to be aggregated (in this specific case, the values on different time steps), pivot_table() can be used, providing an aggregation function (e.g. mean) on how to combine these values.

air_quality2.pivot_table(
    values="value", index="location", columns="parameter", aggfunc="mean"
)

parameter                 no2       pm25
location
BETR801             26.950920  23.169492
FR04014             29.374284        NaN
London Westminster  29.740050  13.443568

### Wide to long format

In [101]:
no2_pivoted = no2.pivot(columns="location", values="value").reset_index()
no2_pivoted.head()

location                  date.utc  BETR801  FR04014  London Westminster
0        2019-04-09 01:00:00+00:00     22.5     24.4                 NaN
1        2019-04-09 02:00:00+00:00     53.5     27.4                67.0
2        2019-04-09 03:00:00+00:00     54.5     34.2                67.0
3        2019-04-09 04:00:00+00:00     34.5     48.5                41.0
4        2019-04-09 05:00:00+00:00     46.5     59.5                41.0

In [102]:
no_2 = no2_pivoted.melt(id_vars="date.utc")
no_2.head()

##The pandas.melt() method on a DataFrame converts the data table from wide format to long format. The column headers become the variable names in a newly created column.

                   date.utc location  value
0 2019-04-09 01:00:00+00:00  BETR801   22.5
1 2019-04-09 02:00:00+00:00  BETR801   53.5
2 2019-04-09 03:00:00+00:00  BETR801   54.5
3 2019-04-09 04:00:00+00:00  BETR801   34.5
4 2019-04-09 05:00:00+00:00  BETR801   46.5

## Data Cleaning (fixing/removing incomplete, incorrect or irrelevant data)

In [103]:
titanic = titanic.drop(columns=["Embarked","Parch"])
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,112053,30.0000,B42
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN

In [105]:
## handle missing data. if is n/a drop the whole row
titanic = titanic.dropna(subset=["Age"])
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,382652,29.1250,NaN
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,112053,30.0000,B42
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN

In [107]:
titanic = titanic.fillna({"Cabin": "0"})
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,382652,29.1250,0
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,112053,30.0000,B42
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,0

In [112]:
##fix inconsistent values
titanic["Sex"] = titanic["Sex"].replace({"female": "FEMALE", "male": "MALE"})
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",MALE,22.0,1,A/5 21171,7.2500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",FEMALE,38.0,1,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss Laina",FEMALE,26.0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",FEMALE,35.0,1,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",MALE,35.0,0,373450,8.0500,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",FEMALE,39.0,0,382652,29.1250,0
886,887,0,2,"Montvila, Rev. Juozas",MALE,27.0,0,211536,13.0000,0
887,888,1,1,"Graham, Miss Margaret Edith",FEMALE,19.0,0,112053,30.0000,B42
889,890,1,1,"Behr, Mr. Karl Howell",MALE,26.0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",MALE,32.0,0,370376,7.7500,0

In [113]:
## standardize text
titanic["Name"] = titanic["Name"].str.lower()
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,0,3,"braund, mr. owen harris",MALE,22.0,1,A/5 21171,7.2500,0
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",FEMALE,38.0,1,PC 17599,71.2833,C85
2,3,1,3,"heikkinen, miss laina",FEMALE,26.0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",FEMALE,35.0,1,113803,53.1000,C123
4,5,0,3,"allen, mr. william henry",MALE,35.0,0,373450,8.0500,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"rice, mrs. william (margaret norton)",FEMALE,39.0,0,382652,29.1250,0
886,887,0,2,"montvila, rev. juozas",MALE,27.0,0,211536,13.0000,0
887,888,1,1,"graham, miss margaret edith",FEMALE,19.0,0,112053,30.0000,B42
889,890,1,1,"behr, mr. karl howell",MALE,26.0,0,111369,30.0000,C148
890,891,0,3,"dooley, mr. patrick",MALE,32.0,0,370376,7.7500,0

In [114]:
## fix data types
titanic["Survived"] = titanic["Survived"].astype(bool)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,False,3,"braund, mr. owen harris",MALE,22.0,1,A/5 21171,7.2500,0
1,2,True,1,"cumings, mrs. john bradley (florence briggs th...",FEMALE,38.0,1,PC 17599,71.2833,C85
2,3,True,3,"heikkinen, miss laina",FEMALE,26.0,0,STON/O2. 3101282,7.9250,0
3,4,True,1,"futrelle, mrs. jacques heath (lily may peel)",FEMALE,35.0,1,113803,53.1000,C123
4,5,False,3,"allen, mr. william henry",MALE,35.0,0,373450,8.0500,0
...,...,...,...,...,...,...,...,...,...,...
885,886,False,3,"rice, mrs. william (margaret norton)",FEMALE,39.0,0,382652,29.1250,0
886,887,False,2,"montvila, rev. juozas",MALE,27.0,0,211536,13.0000,0
887,888,True,1,"graham, miss margaret edith",FEMALE,19.0,0,112053,30.0000,B42
889,890,True,1,"behr, mr. karl howell",MALE,26.0,0,111369,30.0000,C148
890,891,False,3,"dooley, mr. patrick",MALE,32.0,0,370376,7.7500,0

In [116]:
## remove duplicate values
titanic = titanic.drop_duplicates()
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin
0,1,False,3,"braund, mr. owen harris",MALE,22.0,1,A/5 21171,7.2500,0
1,2,True,1,"cumings, mrs. john bradley (florence briggs th...",FEMALE,38.0,1,PC 17599,71.2833,C85
2,3,True,3,"heikkinen, miss laina",FEMALE,26.0,0,STON/O2. 3101282,7.9250,0
3,4,True,1,"futrelle, mrs. jacques heath (lily may peel)",FEMALE,35.0,1,113803,53.1000,C123
4,5,False,3,"allen, mr. william henry",MALE,35.0,0,373450,8.0500,0
...,...,...,...,...,...,...,...,...,...,...
885,886,False,3,"rice, mrs. william (margaret norton)",FEMALE,39.0,0,382652,29.1250,0
886,887,False,2,"montvila, rev. juozas",MALE,27.0,0,211536,13.0000,0
887,888,True,1,"graham, miss margaret edith",FEMALE,19.0,0,112053,30.0000,B42
889,890,True,1,"behr, mr. karl howell",MALE,26.0,0,111369,30.0000,C148
890,891,False,3,"dooley, mr. patrick",MALE,32.0,0,370376,7.7500,0